/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_model/raw_shoe_v1.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    All: THREE.Mesh
    hinter: THREE.Mesh
    ['hinter-oben']: THREE.Mesh
    seiten: THREE.Mesh
    ['seiten-oben']: THREE.Mesh
    vorne: THREE.Mesh
    ['vorne-oben']: THREE.Mesh
    zohle: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/raw_shoe_v1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.908, 0]}>
        <mesh geometry={nodes.All.geometry} material={nodes.All.material} />
        <mesh geometry={nodes.hinter.geometry} material={nodes.hinter.material} />
        <mesh geometry={nodes['hinter-oben'].geometry} material={nodes['hinter-oben'].material} />
        <mesh geometry={nodes.seiten.geometry} material={nodes.seiten.material} />
        <mesh geometry={nodes['seiten-oben'].geometry} material={nodes['seiten-oben'].material} />
        <mesh geometry={nodes.vorne.geometry} material={nodes.vorne.material} />
        <mesh geometry={nodes['vorne-oben'].geometry} material={nodes['vorne-oben'].material} />
        <mesh geometry={nodes.zohle.geometry} material={nodes.zohle.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/raw_shoe_v1.glb')
