/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_model/shoes_material.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    All: THREE.Mesh
    hinter: THREE.Mesh
    ['hinter-oben']: THREE.Mesh
    innen: THREE.Mesh
    schnuehsenkel: THREE.Mesh
    schuhzuenge: THREE.Mesh
    seiten: THREE.Mesh
    ['seiten-hinter']: THREE.Mesh
    ['seiten-oben']: THREE.Mesh
    ['seiten-unten']: THREE.Mesh
    tmpf02s7d6_ply001: THREE.Mesh
    tmpf02s7d6_ply001_1: THREE.Mesh
    tmpf02s7d6_ply001_2: THREE.Mesh
    unten: THREE.Mesh
    vorne: THREE.Mesh
    ['vorne-oben']: THREE.Mesh
  }
  materials: {
    hinter: THREE.MeshStandardMaterial
    hinter_oben: THREE.MeshStandardMaterial
    innen: THREE.MeshStandardMaterial
    schnuehsenkel: THREE.MeshStandardMaterial
    schaum: THREE.MeshStandardMaterial
    seiten: THREE.MeshStandardMaterial
    ['seiten-hinter']: THREE.MeshStandardMaterial
    seiten_oben: THREE.MeshStandardMaterial
    ['seiten-unten']: THREE.MeshStandardMaterial
    sohle: THREE.MeshStandardMaterial
    unten: THREE.MeshStandardMaterial
    vorne: THREE.MeshStandardMaterial
    ['vorne-oben']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/shoes_material.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.908, 0]}>
        <mesh geometry={nodes.All.geometry} material={nodes.All.material} />
        <mesh geometry={nodes.hinter.geometry} material={materials.hinter} />
        <mesh geometry={nodes['hinter-oben'].geometry} material={materials.hinter_oben} />
        <mesh geometry={nodes.innen.geometry} material={materials.innen} />
        <mesh geometry={nodes.schnuehsenkel.geometry} material={materials.schnuehsenkel} />
        <mesh geometry={nodes.schuhzuenge.geometry} material={materials.schaum} />
        <mesh geometry={nodes.seiten.geometry} material={materials.seiten} />
        <mesh geometry={nodes['seiten-hinter'].geometry} material={materials['seiten-hinter']} />
        <mesh geometry={nodes['seiten-oben'].geometry} material={materials.seiten_oben} />
        <mesh geometry={nodes['seiten-unten'].geometry} material={materials['seiten-unten']} />
        <mesh geometry={nodes.unten.geometry} material={materials.unten} />
        <mesh geometry={nodes.vorne.geometry} material={materials.vorne} />
        <mesh geometry={nodes['vorne-oben'].geometry} material={materials['vorne-oben']} />
        <mesh geometry={nodes.tmpf02s7d6_ply001.geometry} material={materials.sohle} />
        <mesh geometry={nodes.tmpf02s7d6_ply001_1.geometry} material={nodes.tmpf02s7d6_ply001_1.material} />
        <mesh geometry={nodes.tmpf02s7d6_ply001_2.geometry} material={materials.sohle} />
      </group>
    </group>
  )
}

useGLTF.preload('/shoes_material.glb')
